version: "3"

tasks:
  build:
    desc: Build the standard extension .jar and standalone executable .jar
    cmds:
      - ./gradlew clean build shadowJar
      - echo "The compiled jars can be found in build/libs/"

  test:
    desc: Run tests for the project
    cmds:
      - ./gradlew test

  clean:
    desc: Clean the build directory
    cmds:
      - ./gradlew clean
